---
  # This play deploys the project to the virtual hosts.
  
- name: Install Python3, pip
  hosts: all
  become: yes
  tasks:
    - name: install the python3 in ansible
      ansible.builtin.package:
        name: python3
        state: latest
    - name: install the python3-venv in ansible
      ansible.builtin.package:
        name: python3-venv
        state: latest
    - name: install the git in ansible
      ansible.builtin.package:
        name: git
        state: latest
    - name: make sure the pip is installed on hosts
      ansible.builtin.package:
        name: python3-pip
        state: present  
     
# Deploy Project 0
- name: Deploy Project 0
  hosts: all
  become: yes
  tasks:
  - name: Clone/Update
    git:
      repo: https://github.com/2105-may24-devops/haoxin-project0
      dest: /home/haoxin/haoxin-project0/
      clone: yes
      update: yes
  - name: Install dependencies  
    ansible.builtin.script: ./requirements.sh
